site_name: sodym

plugins:
  - mkdocstrings
  - mkdocs-jupyter:
      execute: true

nav:
  - index.md
  - Documentation:
    - code_documentation/model_and_components.md
    - code_documentation/stocks.md
    - code_documentation/data_writing_and_plotting.md
  - Examples:
    - examples/example1.py
    - examples/example2.py
    - examples/example3.py
    - examples/example5.py
